[package]
name = "tfjinja"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
config = "0.13"
tera = "1.17"