# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build-win:
    cmds:
      - cargo build --release
  build-mac:
    cmds:
      - cross build --target x86_64-apple-darwin --release
  build-linux:
    cmds:
      - cross build --target x86_64-unknown-linux-gnu --release
  build-all:
    cmds:
      - task: build-win
      - task: build-mac
      - task: build-linux
  run:
    cmds:
      - cargo run